//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.SaleCardControllerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:SaleCardControllerwsdl", ConfigurationName="SaleCardControllerService.SaleCardControllerPortType")]
    public interface SaleCardControllerPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SaleCardControllerwsdl#DoTopupToMerchant", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Web.SaleCardControllerService.TopupToMerchantResponse DoTopupToMerchant(Web.SaleCardControllerService.TopupToMerchantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SaleCardControllerwsdl#DoTopupToMerchant", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Web.SaleCardControllerService.TopupToMerchantResponse> DoTopupToMerchantAsync(Web.SaleCardControllerService.TopupToMerchantRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SaleCardControllerwsdl")]
    public partial class TopupToMerchantRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string merchant_idField;
        
        private string api_usernameField;
        
        private string api_passwordField;
        
        private string binding_fieldField;
        
        private string transaction_idField;
        
        private string card_idField;
        
        private string pin_fieldField;
        
        private string seri_fieldField;
        
        private string data_signField;
        
        private string emailField;
        
        /// <remarks/>
        public string merchant_id {
            get {
                return this.merchant_idField;
            }
            set {
                this.merchant_idField = value;
                this.RaisePropertyChanged("merchant_id");
            }
        }
        
        /// <remarks/>
        public string api_username {
            get {
                return this.api_usernameField;
            }
            set {
                this.api_usernameField = value;
                this.RaisePropertyChanged("api_username");
            }
        }
        
        /// <remarks/>
        public string api_password {
            get {
                return this.api_passwordField;
            }
            set {
                this.api_passwordField = value;
                this.RaisePropertyChanged("api_password");
            }
        }
        
        /// <remarks/>
        public string binding_field {
            get {
                return this.binding_fieldField;
            }
            set {
                this.binding_fieldField = value;
                this.RaisePropertyChanged("binding_field");
            }
        }
        
        /// <remarks/>
        public string transaction_id {
            get {
                return this.transaction_idField;
            }
            set {
                this.transaction_idField = value;
                this.RaisePropertyChanged("transaction_id");
            }
        }
        
        /// <remarks/>
        public string card_id {
            get {
                return this.card_idField;
            }
            set {
                this.card_idField = value;
                this.RaisePropertyChanged("card_id");
            }
        }
        
        /// <remarks/>
        public string pin_field {
            get {
                return this.pin_fieldField;
            }
            set {
                this.pin_fieldField = value;
                this.RaisePropertyChanged("pin_field");
            }
        }
        
        /// <remarks/>
        public string seri_field {
            get {
                return this.seri_fieldField;
            }
            set {
                this.seri_fieldField = value;
                this.RaisePropertyChanged("seri_field");
            }
        }
        
        /// <remarks/>
        public string data_sign {
            get {
                return this.data_signField;
            }
            set {
                this.data_signField = value;
                this.RaisePropertyChanged("data_sign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SaleCardControllerwsdl")]
    public partial class TopupToMerchantResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_codeField;
        
        private string error_messageField;
        
        private string transaction_idField;
        
        private string trans_idField;
        
        private string info_cardField;
        
        private string data_signField;
        
        /// <remarks/>
        public string error_code {
            get {
                return this.error_codeField;
            }
            set {
                this.error_codeField = value;
                this.RaisePropertyChanged("error_code");
            }
        }
        
        /// <remarks/>
        public string error_message {
            get {
                return this.error_messageField;
            }
            set {
                this.error_messageField = value;
                this.RaisePropertyChanged("error_message");
            }
        }
        
        /// <remarks/>
        public string transaction_id {
            get {
                return this.transaction_idField;
            }
            set {
                this.transaction_idField = value;
                this.RaisePropertyChanged("transaction_id");
            }
        }
        
        /// <remarks/>
        public string trans_id {
            get {
                return this.trans_idField;
            }
            set {
                this.trans_idField = value;
                this.RaisePropertyChanged("trans_id");
            }
        }
        
        /// <remarks/>
        public string info_card {
            get {
                return this.info_cardField;
            }
            set {
                this.info_cardField = value;
                this.RaisePropertyChanged("info_card");
            }
        }
        
        /// <remarks/>
        public string data_sign {
            get {
                return this.data_signField;
            }
            set {
                this.data_signField = value;
                this.RaisePropertyChanged("data_sign");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SaleCardControllerPortTypeChannel : Web.SaleCardControllerService.SaleCardControllerPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaleCardControllerPortTypeClient : System.ServiceModel.ClientBase<Web.SaleCardControllerService.SaleCardControllerPortType>, Web.SaleCardControllerService.SaleCardControllerPortType {
        
        public SaleCardControllerPortTypeClient() {
        }
        
        public SaleCardControllerPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaleCardControllerPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleCardControllerPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleCardControllerPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Web.SaleCardControllerService.TopupToMerchantResponse DoTopupToMerchant(Web.SaleCardControllerService.TopupToMerchantRequest request) {
            return base.Channel.DoTopupToMerchant(request);
        }
        
        public System.Threading.Tasks.Task<Web.SaleCardControllerService.TopupToMerchantResponse> DoTopupToMerchantAsync(Web.SaleCardControllerService.TopupToMerchantRequest request) {
            return base.Channel.DoTopupToMerchantAsync(request);
        }
    }
}
