// <auto-generated />
namespace VD.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class phac_do_cua_toi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phac_do_cua_toi));
        
        string IMigrationMetadata.Id
        {
            get { return "201709201538338_phac_do_cua_toi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
