// <auto-generated />
namespace VD.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mg_guiemaildonhang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg_guiemaildonhang));
        
        string IMigrationMetadata.Id
        {
            get { return "201712171000548_mg_guiemaildonhang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
