//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class mui {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mui() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VD.Lang.mui", typeof(mui).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Management.
        /// </summary>
        public static string account_managemant {
            get {
                return ResourceManager.GetString("account_managemant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active job.
        /// </summary>
        public static string active_job {
            get {
                return ResourceManager.GetString("active_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string any {
            get {
                return ResourceManager.GetString("any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application management.
        /// </summary>
        public static string application_management {
            get {
                return ResourceManager.GetString("application_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;label class=&quot;label label-success&quot;&gt;Approved&lt;/label&gt;.
        /// </summary>
        public static string approce_ok {
            get {
                return ResourceManager.GetString("approce_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;label class=&quot;label label-warning&quot;&gt;Pending&lt;/label&gt;.
        /// </summary>
        public static string approce_wait {
            get {
                return ResourceManager.GetString("approce_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acttach CV file.
        /// </summary>
        public static string attach_cv {
            get {
                return ResourceManager.GetString("attach_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: With your CV applied, employers can view your CV that you have uploaded the latest!.
        /// </summary>
        public static string attach_cv_note {
            get {
                return ResourceManager.GetString("attach_cv_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string btn_apply {
            get {
                return ResourceManager.GetString("btn_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase wallet.
        /// </summary>
        public static string btn_purchase_wallet {
            get {
                return ResourceManager.GetString("btn_purchase_wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or send request to purchase wallet.
        /// </summary>
        public static string btn_purchase_wallet_note {
            get {
                return ResourceManager.GetString("btn_purchase_wallet_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string btn_register {
            get {
                return ResourceManager.GetString("btn_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btn_search {
            get {
                return ResourceManager.GetString("btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string btn_send {
            get {
                return ResourceManager.GetString("btn_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Account.
        /// </summary>
        public static string btn_upgrade_account {
            get {
                return ResourceManager.GetString("btn_upgrade_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV OF CANDIDATE.
        /// </summary>
        public static string cadidate_cv {
            get {
                return ResourceManager.GetString("cadidate_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION OF CANDIDATE.
        /// </summary>
        public static string cadidate_information {
            get {
                return ResourceManager.GetString("cadidate_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate.
        /// </summary>
        public static string candidate {
            get {
                return ResourceManager.GetString("candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates.
        /// </summary>
        public static string candidates {
            get {
                return ResourceManager.GetString("candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha code is invalid!.
        /// </summary>
        public static string captcha_fail {
            get {
                return ResourceManager.GetString("captcha_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change picture.
        /// </summary>
        public static string change_picture {
            get {
                return ResourceManager.GetString("change_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chef.
        /// </summary>
        public static string Chef {
            get {
                return ResourceManager.GetString("Chef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Location--.
        /// </summary>
        public static string citi_select {
            get {
                return ResourceManager.GetString("citi_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to change profile image.
        /// </summary>
        public static string click_here_change_image {
            get {
                return ResourceManager.GetString("click_here_change_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string clients {
            get {
                return ResourceManager.GetString("clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About company.
        /// </summary>
        public static string company_about {
            get {
                return ResourceManager.GetString("company_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company email.
        /// </summary>
        public static string company_email {
            get {
                return ResourceManager.GetString("company_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company location.
        /// </summary>
        public static string company_location {
            get {
                return ResourceManager.GetString("company_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company phone.
        /// </summary>
        public static string company_phone {
            get {
                return ResourceManager.GetString("company_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has not activated because of unpaid or end date! Please contact the customer service department for assistance with this problem. Thank you!.
        /// </summary>
        public static string company_unpaid {
            get {
                return ResourceManager.GetString("company_unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this item ?.
        /// </summary>
        public static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant.
        /// </summary>
        public static string consultant {
            get {
                return ResourceManager.GetString("consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string contact_address {
            get {
                return ResourceManager.GetString("contact_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha code.
        /// </summary>
        public static string contact_captcha {
            get {
                return ResourceManager.GetString("contact_captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string contact_company_name {
            get {
                return ResourceManager.GetString("contact_company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string contact_email {
            get {
                return ResourceManager.GetString("contact_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        public static string contact_inquiry {
            get {
                return ResourceManager.GetString("contact_inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiries/ Comments.
        /// </summary>
        public static string contact_inquiry_note {
            get {
                return ResourceManager.GetString("contact_inquiry_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string contact_name {
            get {
                return ResourceManager.GetString("contact_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string contact_person {
            get {
                return ResourceManager.GetString("contact_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string contact_phone {
            get {
                return ResourceManager.GetString("contact_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string contact_subject {
            get {
                return ResourceManager.GetString("contact_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic/subject.
        /// </summary>
        public static string contact_subject_note {
            get {
                return ResourceManager.GetString("contact_subject_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for contact us!.
        /// </summary>
        public static string contact_success {
            get {
                return ResourceManager.GetString("contact_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our clients are Multinational Companies, FDI Enterprises, Representative Offices, and local prestigious companies which locate in big cities of Vietnam such as: HCMC, Da Nang, Dong Nai, Vung Tau, Can Tho and Ha Noi..
        /// </summary>
        public static string create_cv_note {
            get {
                return ResourceManager.GetString("create_cv_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string create_new {
            get {
                return ResourceManager.GetString("create_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV applied.
        /// </summary>
        public static string cv_applied {
            get {
                return ResourceManager.GetString("cv_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employers are allowed to watch for free.
        /// </summary>
        public static string cv_applied_view_free {
            get {
                return ResourceManager.GetString("cv_applied_view_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter full data or upload to your profile.
        /// </summary>
        public static string cv_data_attach {
            get {
                return ResourceManager.GetString("cv_data_attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Management.
        /// </summary>
        public static string cv_managemant {
            get {
                return ResourceManager.GetString("cv_managemant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Saved.
        /// </summary>
        public static string cv_saved_management {
            get {
                return ResourceManager.GetString("cv_saved_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV viewed.
        /// </summary>
        public static string cv_viewed {
            get {
                return ResourceManager.GetString("cv_viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        public static string date_modified {
            get {
                return ResourceManager.GetString("date_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Posted.
        /// </summary>
        public static string date_post {
            get {
                return ResourceManager.GetString("date_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees.
        /// </summary>
        public static string degree {
            get {
                return ResourceManager.GetString("degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Degrees--.
        /// </summary>
        public static string degree_select {
            get {
                return ResourceManager.GetString("degree_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other degree.
        /// </summary>
        public static string degreeText {
            get {
                return ResourceManager.GetString("degreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Job.
        /// </summary>
        public static string edit_job {
            get {
                return ResourceManager.GetString("edit_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string edit_profile {
            get {
                return ResourceManager.GetString("edit_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your CV was successfully updated !.
        /// </summary>
        public static string edit_your_cv_success {
            get {
                return ResourceManager.GetString("edit_your_cv_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your CV was successfully updated. Please wait for our approvement. .
        /// </summary>
        public static string edit_your_cv_success_approve {
            get {
                return ResourceManager.GetString("edit_your_cv_success_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Background.
        /// </summary>
        public static string educational {
            get {
                return ResourceManager.GetString("educational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employers.
        /// </summary>
        public static string employees {
            get {
                return ResourceManager.GetString("employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer wallet.
        /// </summary>
        public static string employer_wallet {
            get {
                return ResourceManager.GetString("employer_wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 item.
        /// </summary>
        public static string empty_record {
            get {
                return ResourceManager.GetString("empty_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string fee_description {
            get {
                return ResourceManager.GetString("fee_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string fee_detail_discount {
            get {
                return ResourceManager.GetString("fee_detail_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay (VND).
        /// </summary>
        public static string fee_detail_pay {
            get {
                return ResourceManager.GetString("fee_detail_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (VND).
        /// </summary>
        public static string fee_detail_price {
            get {
                return ResourceManager.GetString("fee_detail_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string fee_detail_sale {
            get {
                return ResourceManager.GetString("fee_detail_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving (VND).
        /// </summary>
        public static string fee_detail_saving {
            get {
                return ResourceManager.GetString("fee_detail_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string fee_detail_score {
            get {
                return ResourceManager.GetString("fee_detail_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string fee_gate {
            get {
                return ResourceManager.GetString("fee_gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee label.
        /// </summary>
        public static string fee_label {
            get {
                return ResourceManager.GetString("fee_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee List.
        /// </summary>
        public static string fee_list {
            get {
                return ResourceManager.GetString("fee_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN SCORE.
        /// </summary>
        public static string fee_min_score {
            get {
                return ResourceManager.GetString("fee_min_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string fee_price {
            get {
                return ResourceManager.GetString("fee_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Profile/1 unit.
        /// </summary>
        public static string fee_score_filter_profile {
            get {
                return ResourceManager.GetString("fee_score_filter_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        public static string fee_score_label_hot {
            get {
                return ResourceManager.GetString("fee_score_label_hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string fee_score_label_new {
            get {
                return ResourceManager.GetString("fee_score_label_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string fee_score_label_top {
            get {
                return ResourceManager.GetString("fee_score_label_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string fee_score_label_urgent {
            get {
                return ResourceManager.GetString("fee_score_label_urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Job/Recruitment/1 unit.
        /// </summary>
        public static string fee_score_post_recruitment {
            get {
                return ResourceManager.GetString("fee_score_post_recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee service.
        /// </summary>
        public static string fee_service {
            get {
                return ResourceManager.GetString("fee_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for feedback us!.
        /// </summary>
        public static string feedback_success {
            get {
                return ResourceManager.GetString("feedback_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For candidates.
        /// </summary>
        public static string for_candidates {
            get {
                return ResourceManager.GetString("for_candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For employers.
        /// </summary>
        public static string for_employees {
            get {
                return ResourceManager.GetString("for_employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string forgot_password {
            get {
                return ResourceManager.GetString("forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string full_name {
            get {
                return ResourceManager.GetString("full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not required.
        /// </summary>
        public static string gender_all {
            get {
                return ResourceManager.GetString("gender_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string gender_female {
            get {
                return ResourceManager.GetString("gender_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string gender_male {
            get {
                return ResourceManager.GetString("gender_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Gender --.
        /// </summary>
        public static string gender_select {
            get {
                return ResourceManager.GetString("gender_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0} items.
        /// </summary>
        public static string gridInfo {
            get {
                return ResourceManager.GetString("gridInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use headhunting service.
        /// </summary>
        public static string headhunting_service {
            get {
                return ResourceManager.GetString("headhunting_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable use headhunting service.
        /// </summary>
        public static string headhunting_service_enable {
            get {
                return ResourceManager.GetString("headhunting_service_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headhunting Service Fee.
        /// </summary>
        public static string headhunting_service_fee {
            get {
                return ResourceManager.GetString("headhunting_service_fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to host a dinner.
        /// </summary>
        public static string host_a_dinner {
            get {
                return ResourceManager.GetString("host_a_dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Jobs.
        /// </summary>
        public static string hot_jobs {
            get {
                return ResourceManager.GetString("hot_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string industry {
            get {
                return ResourceManager.GetString("industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry focus.
        /// </summary>
        public static string industry_focus {
            get {
                return ResourceManager.GetString("industry_focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Industry--.
        /// </summary>
        public static string industry_select {
            get {
                return ResourceManager.GetString("industry_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-industry.
        /// </summary>
        public static string industry_sub {
            get {
                return ResourceManager.GetString("industry_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is cooking.
        /// </summary>
        public static string is_cooking {
            get {
                return ResourceManager.GetString("is_cooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are Korean Candidates.
        /// </summary>
        public static string is_korean_candidates {
            get {
                return ResourceManager.GetString("is_korean_candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you KOREAN EMPLOYER? Your CV will be more noticeable candidate.
        /// </summary>
        public static string is_korean_employer {
            get {
                return ResourceManager.GetString("is_korean_employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit.
        /// </summary>
        public static string job_benefit {
            get {
                return ResourceManager.GetString("job_benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string job_company_name {
            get {
                return ResourceManager.GetString("job_company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job description.
        /// </summary>
        public static string job_description {
            get {
                return ResourceManager.GetString("job_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job description management.
        /// </summary>
        public static string job_description_management {
            get {
                return ResourceManager.GetString("job_description_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You saved this job.
        /// </summary>
        public static string job_has_saved {
            get {
                return ResourceManager.GetString("job_has_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career goals.
        /// </summary>
        public static string job_information {
            get {
                return ResourceManager.GetString("job_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Management.
        /// </summary>
        public static string job_management {
            get {
                return ResourceManager.GetString("job_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs other.
        /// </summary>
        public static string job_other {
            get {
                return ResourceManager.GetString("job_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Overview.
        /// </summary>
        public static string job_overview {
            get {
                return ResourceManager.GetString("job_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job requirements.
        /// </summary>
        public static string job_requirement {
            get {
                return ResourceManager.GetString("job_requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save jobs only for candidates.
        /// </summary>
        public static string job_saved_only_candidate {
            get {
                return ResourceManager.GetString("job_saved_only_candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save job successfull!.
        /// </summary>
        public static string job_saved_success {
            get {
                return ResourceManager.GetString("job_saved_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has not activated because of unpaid or end date! Please contact the customer service department for assistance with this problem. Thank you!.
        /// </summary>
        public static string job_status_unpaid {
            get {
                return ResourceManager.GetString("job_status_unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean candidates.
        /// </summary>
        public static string korean_candidates {
            get {
                return ResourceManager.GetString("korean_candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Viewed.
        /// </summary>
        public static string last_view {
            get {
                return ResourceManager.GetString("last_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Level--.
        /// </summary>
        public static string level_select {
            get {
                return ResourceManager.GetString("level_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employers.
        /// </summary>
        public static string login_employees_label {
            get {
                return ResourceManager.GetString("login_employees_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        public static string Meals {
            get {
                return ResourceManager.GetString("Meals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Not Enough.
        /// </summary>
        public static string money_no_enough {
            get {
                return ResourceManager.GetString("money_no_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string my_profile {
            get {
                return ResourceManager.GetString("my_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        public static string navigate {
            get {
                return ResourceManager.GetString("navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW CV.
        /// </summary>
        public static string new_cv {
            get {
                return ResourceManager.GetString("new_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New jobs.
        /// </summary>
        public static string new_jobs {
            get {
                return ResourceManager.GetString("new_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not have an account?.
        /// </summary>
        public static string no_account {
            get {
                return ResourceManager.GetString("no_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string no_data {
            get {
                return ResourceManager.GetString("no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not selected.
        /// </summary>
        public static string not_selected {
            get {
                return ResourceManager.GetString("not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR CLIENTS.
        /// </summary>
        public static string our_clients {
            get {
                return ResourceManager.GetString("our_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our services.
        /// </summary>
        public static string our_services {
            get {
                return ResourceManager.GetString("our_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR HOT JOBS.
        /// </summary>
        public static string out_hot_jobs {
            get {
                return ResourceManager.GetString("out_hot_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string package {
            get {
                return ResourceManager.GetString("package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string password_confirm {
            get {
                return ResourceManager.GetString("password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string password_new {
            get {
                return ResourceManager.GetString("password_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string password_new_confirm {
            get {
                return ResourceManager.GetString("password_new_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string password_old {
            get {
                return ResourceManager.GetString("password_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree to pay and view resume.
        /// </summary>
        public static string pay_to_view_agree {
            get {
                return ResourceManager.GetString("pay_to_view_agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel &amp; back.
        /// </summary>
        public static string pay_to_view_cancel {
            get {
                return ResourceManager.GetString("pay_to_view_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View contact.
        /// </summary>
        public static string pay_to_view_contact {
            get {
                return ResourceManager.GetString("pay_to_view_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pay points to see this resume.
        /// </summary>
        public static string pay_to_view_cv {
            get {
                return ResourceManager.GetString("pay_to_view_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price scores.
        /// </summary>
        public static string pay_to_view_price {
            get {
                return ResourceManager.GetString("pay_to_view_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Amount.
        /// </summary>
        public static string pay_to_view_remain {
            get {
                return ResourceManager.GetString("pay_to_view_remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Score.
        /// </summary>
        public static string pay_to_view_score {
            get {
                return ResourceManager.GetString("pay_to_view_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough points to view the candidate profile.
        /// </summary>
        public static string pay_view_cv_error {
            get {
                return ResourceManager.GetString("pay_view_cv_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment successfully!.
        /// </summary>
        public static string pay_view_success {
            get {
                return ResourceManager.GetString("pay_view_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of recruits.
        /// </summary>
        public static string person {
            get {
                return ResourceManager.GetString("person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Please login to view salary].
        /// </summary>
        public static string please_login_view_salary {
            get {
                return ResourceManager.GetString("please_login_view_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select.
        /// </summary>
        public static string please_select {
            get {
                return ResourceManager.GetString("please_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select.
        /// </summary>
        public static string pleaseSelect {
            get {
                return ResourceManager.GetString("pleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a job.
        /// </summary>
        public static string post_a_job {
            get {
                return ResourceManager.GetString("post_a_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Jobs &amp; Find Talents Service Fee.
        /// </summary>
        public static string post_job_and_find_talents_services_fee {
            get {
                return ResourceManager.GetString("post_job_and_find_talents_services_fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Jobs &amp; Find Talents.
        /// </summary>
        public static string post_job_find_talents {
            get {
                return ResourceManager.GetString("post_job_find_talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted Jobs.
        /// </summary>
        public static string posted_jobs {
            get {
                return ResourceManager.GetString("posted_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Province --.
        /// </summary>
        public static string province_select {
            get {
                return ResourceManager.GetString("province_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Service History.
        /// </summary>
        public static string purchase_history {
            get {
                return ResourceManager.GetString("purchase_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your purchase request successfully.
        /// </summary>
        public static string purchase_wallet_message {
            get {
                return ResourceManager.GetString("purchase_wallet_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the field {0} must be between {1} and {2}.
        /// </summary>
        public static string range {
            get {
                return ResourceManager.GetString("range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        public static string register_now {
            get {
                return ResourceManager.GetString("register_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field {0} is required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Salary range--.
        /// </summary>
        public static string salary_select {
            get {
                return ResourceManager.GetString("salary_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Advertisement.
        /// </summary>
        public static string score_advertisement {
            get {
                return ResourceManager.GetString("score_advertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string score_current {
            get {
                return ResourceManager.GetString("score_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Filter Profile.
        /// </summary>
        public static string score_filter_profile {
            get {
                return ResourceManager.GetString("score_filter_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score paid.
        /// </summary>
        public static string score_paid {
            get {
                return ResourceManager.GetString("score_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Post Job/Recruitment.
        /// </summary>
        public static string score_post_recruitment {
            get {
                return ResourceManager.GetString("score_post_recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string score_total {
            get {
                return ResourceManager.GetString("score_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for a dinner.
        /// </summary>
        public static string search_for_a_dinner {
            get {
                return ResourceManager.GetString("search_for_a_dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search jobs.
        /// </summary>
        public static string search_job {
            get {
                return ResourceManager.GetString("search_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        public static string search_job_title {
            get {
                return ResourceManager.GetString("search_job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search resume.
        /// </summary>
        public static string search_resume {
            get {
                return ResourceManager.GetString("search_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select thumbnail.
        /// </summary>
        public static string select_thumbnail {
            get {
                return ResourceManager.GetString("select_thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service price list.
        /// </summary>
        public static string service_price_list {
            get {
                return ResourceManager.GetString("service_price_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may not be longer than {1} characters.
        /// </summary>
        public static string strlen {
            get {
                return ResourceManager.GetString("strlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuff.
        /// </summary>
        public static string Stuff {
            get {
                return ResourceManager.GetString("Stuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT A VACANCY.
        /// </summary>
        public static string submit_a_vacancy {
            get {
                return ResourceManager.GetString("submit_a_vacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit CV.
        /// </summary>
        public static string submit_cv {
            get {
                return ResourceManager.GetString("submit_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit job decription.
        /// </summary>
        public static string submit_job_decription {
            get {
                return ResourceManager.GetString("submit_job_decription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your CV.
        /// </summary>
        public static string submit_your_cv {
            get {
                return ResourceManager.GetString("submit_your_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your CV was successfully submitted!.
        /// </summary>
        public static string submit_your_cv_success {
            get {
                return ResourceManager.GetString("submit_your_cv_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your CV was successfully submitted. Please wait for our approvement..
        /// </summary>
        public static string submit_your_cv_success_wait_approve {
            get {
                return ResourceManager.GetString("submit_your_cv_success_wait_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click here if you want to find Korean candidates
        ///.
        /// </summary>
        public static string tick_here_to_search_korean_candidates {
            get {
                return ResourceManager.GetString("tick_here_to_search_korean_candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string tips {
            get {
                return ResourceManager.GetString("tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for candidates.
        /// </summary>
        public static string tips_for_candidates {
            get {
                return ResourceManager.GetString("tips_for_candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for employers.
        /// </summary>
        public static string tips_for_emloyees {
            get {
                return ResourceManager.GetString("tips_for_emloyees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string title_Active {
            get {
                return ResourceManager.GetString("title_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string title_approve {
            get {
                return ResourceManager.GetString("title_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Applied.
        /// </summary>
        public static string title_date_applied {
            get {
                return ResourceManager.GetString("title_date_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date saved.
        /// </summary>
        public static string title_date_saved {
            get {
                return ResourceManager.GetString("title_date_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string title_Industry {
            get {
                return ResourceManager.GetString("title_Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        public static string title_Job {
            get {
                return ResourceManager.GetString("title_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string title_Level {
            get {
                return ResourceManager.GetString("title_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string title_No {
            get {
                return ResourceManager.GetString("title_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string title_Salary {
            get {
                return ResourceManager.GetString("title_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string title_Status {
            get {
                return ResourceManager.GetString("title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string title_Update {
            get {
                return ResourceManager.GetString("title_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string title_View {
            get {
                return ResourceManager.GetString("title_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working type.
        /// </summary>
        public static string title_Working_type {
            get {
                return ResourceManager.GetString("title_Working_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top jobs.
        /// </summary>
        public static string top_jobs {
            get {
                return ResourceManager.GetString("top_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type postion.
        /// </summary>
        public static string type_position {
            get {
                return ResourceManager.GetString("type_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your account.
        /// </summary>
        public static string update_your_account {
            get {
                return ResourceManager.GetString("update_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your CV.
        /// </summary>
        public static string update_your_cv {
            get {
                return ResourceManager.GetString("update_your_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload file.
        /// </summary>
        public static string upload_file {
            get {
                return ResourceManager.GetString("upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more.
        /// </summary>
        public static string view_more {
            get {
                return ResourceManager.GetString("view_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vip jobs $1000+.
        /// </summary>
        public static string vip_jobs_1000plus {
            get {
                return ResourceManager.GetString("vip_jobs_1000plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current wallet scores.
        /// </summary>
        public static string wallet_current {
            get {
                return ResourceManager.GetString("wallet_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Remaining Amount.
        /// </summary>
        public static string wallet_remaining_amount {
            get {
                return ResourceManager.GetString("wallet_remaining_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME TO BEST HR SOLUTION.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Experience.
        /// </summary>
        public static string work_experience {
            get {
                return ResourceManager.GetString("work_experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Location.
        /// </summary>
        public static string work_location {
            get {
                return ResourceManager.GetString("work_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Work Type--.
        /// </summary>
        public static string work_type_select {
            get {
                return ResourceManager.GetString("work_type_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string year_experience {
            get {
                return ResourceManager.GetString("year_experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Year Experience--.
        /// </summary>
        public static string year_experience_select {
            get {
                return ResourceManager.GetString("year_experience_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your CV.
        /// </summary>
        public static string your_cv {
            get {
                return ResourceManager.GetString("your_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your CV to apply.
        /// </summary>
        public static string your_cv_select {
            get {
                return ResourceManager.GetString("your_cv_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR INFORMATION.
        /// </summary>
        public static string your_infomation {
            get {
                return ResourceManager.GetString("your_infomation", resourceCulture);
            }
        }
    }
}
