//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mui_sys {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class mui_sys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mui_sys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VD.Lang.mui_sys", typeof(mui_sys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any.
        /// </summary>
        public static string any {
            get {
                return ResourceManager.GetString("any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change picture.
        /// </summary>
        public static string change_picture {
            get {
                return ResourceManager.GetString("change_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chef.
        /// </summary>
        public static string Chef {
            get {
                return ResourceManager.GetString("Chef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure you want to delete this item ?.
        /// </summary>
        public static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string create_new {
            get {
                return ResourceManager.GetString("create_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0} items.
        /// </summary>
        public static string gridInfo {
            get {
                return ResourceManager.GetString("gridInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to host a dinner.
        /// </summary>
        public static string host_a_dinner {
            get {
                return ResourceManager.GetString("host_a_dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is cooking.
        /// </summary>
        public static string is_cooking {
            get {
                return ResourceManager.GetString("is_cooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        public static string Meals {
            get {
                return ResourceManager.GetString("Meals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not selected.
        /// </summary>
        public static string not_selected {
            get {
                return ResourceManager.GetString("not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select.
        /// </summary>
        public static string please_select {
            get {
                return ResourceManager.GetString("please_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select.
        /// </summary>
        public static string pleaseSelect {
            get {
                return ResourceManager.GetString("pleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the field {0} must be between {1} and {2}.
        /// </summary>
        public static string range {
            get {
                return ResourceManager.GetString("range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field {0} is required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for a dinner.
        /// </summary>
        public static string search_for_a_dinner {
            get {
                return ResourceManager.GetString("search_for_a_dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select thumbnail.
        /// </summary>
        public static string select_thumbnail {
            get {
                return ResourceManager.GetString("select_thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row per page.
        /// </summary>
        public static string setting_row_per_page {
            get {
                return ResourceManager.GetString("setting_row_per_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row per page of CV.
        /// </summary>
        public static string setting_rpp_cv {
            get {
                return ResourceManager.GetString("setting_rpp_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row per page of CV apply to job.
        /// </summary>
        public static string setting_rpp_cv_apply_job {
            get {
                return ResourceManager.GetString("setting_rpp_cv_apply_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row per page of industry focus.
        /// </summary>
        public static string setting_rpp_industry_focus {
            get {
                return ResourceManager.GetString("setting_rpp_industry_focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row per page of Job.
        /// </summary>
        public static string setting_rpp_job {
            get {
                return ResourceManager.GetString("setting_rpp_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search resume.
        /// </summary>
        public static string setting_rpp_search_resume {
            get {
                return ResourceManager.GetString("setting_rpp_search_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ssl.
        /// </summary>
        public static string setting_smpt_enable_ssl {
            get {
                return ResourceManager.GetString("setting_smpt_enable_ssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string setting_smpt_host {
            get {
                return ResourceManager.GetString("setting_smpt_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string setting_smpt_port {
            get {
                return ResourceManager.GetString("setting_smpt_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default credentials.
        /// </summary>
        public static string setting_smpt_use_default_credentials {
            get {
                return ResourceManager.GetString("setting_smpt_use_default_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email system.
        /// </summary>
        public static string setting_sys_email {
            get {
                return ResourceManager.GetString("setting_sys_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email robot.
        /// </summary>
        public static string setting_sys_email_robot {
            get {
                return ResourceManager.GetString("setting_sys_email_robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password email robot.
        /// </summary>
        public static string setting_sys_email_robot_pw {
            get {
                return ResourceManager.GetString("setting_sys_email_robot_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may not be longer than {1} characters.
        /// </summary>
        public static string strlen {
            get {
                return ResourceManager.GetString("strlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuff.
        /// </summary>
        public static string Stuff {
            get {
                return ResourceManager.GetString("Stuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload file.
        /// </summary>
        public static string upload_file {
            get {
                return ResourceManager.GetString("upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
