//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using VD.Data.Entity.MF;

namespace VD.Data.Entity
{
    public class User : BaseEntity
    {
        public User()
        {
          
        }
        [Display(Name="Tài khoản")]
        public string Username { get; set; }
        [Display(Name = "Mật khẩu")]
        public string Password { get; set; }
        [Display(Name = "Số điện thoại")]
        public string Phone { get; set; }
        [Display(Name = "Địa chỉ")]
        public string Address { get; set; }
        [Display(Name = "Họ và tên")]
        public string Fullname { get; set; }

        [Display(Name = "Ví tiền")]
        public int ViTien { get; set; }
        [Display(Name = "Thành viên VIP")]
        public bool IsVip1 { get; set; }
        [Display(Name = "Ngày lên VIP")]
        public DateTime? NgayVip { get; set; }
        [Display(Name = "Chú thích VIP")]
        public string ChuThichVip { get; set; }
        //role
        [Display(Name = "Quyền hạn")]
        public int RoleId { get; set; }
        [ForeignKey("RoleId")]
        public virtual Role Role { get; set; }

        //status
        [Display(Name = "Trạng thái")]
        public int UserStatusId { get; set; }
        [ForeignKey("UserStatusId")]
        public virtual UserStatus UserStatus { get; set; }


        //bs


        [Display(Name = "Danh xưng")]
        public string XungDanh { get; set; }


        [Display(Name = "Họ (*)")]
        public string Ho { get; set; }


        [Display(Name = "Tên (*)")]
        public string Ten { get; set; }



        [Display(Name = "Tỉnh thành")]
        public int? ProvinceId { get; set; }
        [ForeignKey("ProvinceId")]

        public virtual Province Province { get; set; }

        [Display(Name = "Phường xã")]

        public int? WardId { get; set; }
        [ForeignKey("WardId")]
        public virtual Ward Ward { get; set; }


        [Display(Name = "Quận huyện")]
        public int? DistrictId { get; set; }
        [ForeignKey("DistrictId")]
        public virtual District District { get; set; }

        public static User[] seed()
        {
            int genid = 0;
            return new User[]
            {
                new User()
                {
                    Id = ++genid,
                    RoleId = 1,
                    UserStatusId = 1,
                    Username = "admin",
                    Password = "104255020101247154213024095114123176100126129011",
                    ViTien = 0,
                    IsVip1 = false,
                },
                new User()
                {
                    Id = ++genid,
                    RoleId = 2,
                    UserStatusId = 2,
                    Username = "user",
                    Password = "104255020101247154213024095114123176100126129011",
                    ViTien = 0,
                    IsVip1 = false,
                },
            };
        }
    }
}
